services:
  db:
    container_name: wheelz_auth_uservice_local_db
    image: mysql
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wheelz-auth-service-local-volume:/var/lib/mysql

volumes:
  wheelz-auth-service-local-volume:
